### ISSUE TITLE
Set up this repository to auto-deploy to the server

### ISSUE THREAD

**Issue by domenic** [whatwg/participate.whatwg.org#6]
This is a follow-up on https://github.com/whatwg/misc-server/pull/53.

After autodeploy we should use pm2 to restart.

Ideally we should autodeploy private-config.json from a private repository as well? That can be done later though.

@foolip, I was thinking of just setting up a Travis file that does rsync on the file contents and then uses SSH to execute the restart command. The SSH key would be encrypted in the same way we do for specs. Any thoughts or concerns?

**Comment by foolip** [comment]
In the end something needs to SSH in, so that sounds good. Webhook is the only other option, but that depends on noembed working so can't be used to recover from problems.

One other possibility is trying to tie the whole noembed setup together in a single repo and deploy that as a whole, perhaps using docker. But I haven't done anything like that, so I'd have to learn how to do a graceful+fast restart etc.
